# Generated by Django 4.1 on 2022-08-20 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0004_remove_category_price"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table="category",
        ),
        migrations.AlterModelTable(
            name="order",
            table="order",
        ),
        migrations.AlterModelTable(
            name="product",
            table="product",
        ),
    ]
