# Generated by Django 4.1 on 2022-08-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0005_alter_category_table_alter_order_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cancel_order",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="is_status",
            field=models.CharField(
                choices=[("active", "active"), ("inactive", "inactive")],
                max_length=150,
                null=True,
            ),
        ),
    ]
