# Generated by Django 4.1 on 2022-08-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0006_order_cancel_order_order_is_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="cancel_order",
            field=models.DateTimeField(default=None),
        ),
    ]
