# Generated by Django 4.1 on 2022-08-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0008_alter_order_is_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancel_order',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
