# Generated by Django 4.1 on 2022-08-28 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0009_alter_order_cancel_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_status',
        ),
    ]
