# Generated by Django 4.1 on 2022-08-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0010_remove_order_is_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancel_order',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
